### ISSUE TITLE
API reference - transfer TS docs into markdown

### ISSUE THREAD

**Issue by d-ivashchuk** [lost-pixel/lost-pixel#153]
### Mode

Other

### Feature description

We are already having great documentation done in our ts types. The task here would be just to move those things into the markdown for our API reference. I've already started with it to have some good example of how things might look like!

https://github.com/lost-pixel/lost-pixel/blob/main/docs/api-reference/lost-pixel.config.js-or-ts.md

**Comment by sumerp16** [comment]
Do you still need help with this?

**Comment by d-ivashchuk** [comment]
nope @sumerp16, all good, we did it manually with some help of ChatGPT :D
