### ISSUE TITLE
Platform feedback

### ISSUE THREAD

**Issue by sandstrom** [lost-pixel/lost-pixel#171]
Didn't find an email, so sending my feedback here.

When you plan the platform architecture, try to structure it in a way where you don't need source-code access to our code.

Ideally, a Github Actions job (or similar) would (a) push the photos to your platform, or it would (b) send a full HTML/CSS/JS package along with an URL path to you.

That way, you don't have access to our source code, you don't have to worry that much about being hacked and it would be much easier to convince our security team to adopt your product.

Also, the CLI tool that would be used in our Github actions runner should preferably be open-source (for inspection) and pinnable (via e.g. NPM), so that if you get hacked it will be harder for a malicious actor to roll out an evil update of that tool.

**Comment by d-ivashchuk** [comment]
hey @sandstrom! awesome that you found time to provide the feedback, thanks a lot! In the current architecture, we are working with repository-held baseline images which means that updating them through the platform needs write access to the repo we are working with. We are already wrapping up the next version of the platform that would allow you to just send images and not be concerned about giving us source-code access. 

Currently, lost-pixel IS the action that generates the images & compares them. It is available via npm and actions marketplace and is pinnable! You can use the lost-pixel visual regression testing flow without a platform at the moment and be fully secure in terms of the source code as you would be responsible for running everything on your CI premises.

**Comment by d-ivashchuk** [comment]
@sandstrom precisely! I will get back to you here when we ship the open beta of the platform that will cover all the problematic spots that we explored in this conversation! Closing the issue for now, feel free to ping me directly for any questions **dimitri@lost-pixel.com**

**Comment by sandstrom** [comment]
Thanks @d-ivashchuk !
