### ISSUE TITLE
Missing timeout on story collection 

### ISSUE THREAD

**Issue by chriskalmar** [lost-pixel/lost-pixel#184]
### Bug description

When the Storybook build is broken, the story collection process seems to be neverending.
I simple timeout should 

### How to reproduce

1. run broken storybook (or just any page that has no stories)
2. run lostpixel
3. process is hanging at `Trying to collect stories via window object`

### Expected behavior

Should fail after a defined timeout

**Comment by Capocaccia** [comment]
Ill take this one!

**Comment by joaogarin** [comment]
Is this one still relevant? I see that there is a timeout of 30sec that comes I think from playwright-core

``` 
page.waitForFunction: Timeout 30000ms exceeded.
```

 is the main goal here having a specific timeout that is handled by lost-pixel here https://github.com/lost-pixel/lost-pixel/blob/main/src/crawler/storybook.ts#L273 and not playwright?  🤔

**Comment by d-ivashchuk** [comment]
I think this might not be so relevant anymore as we throw errors on timeouts. At least I've never experienced a broken storybook resulting in never ending run lately 😀
