### ISSUE TITLE
Ability to skip screenshot for individual stories

### ISSUE THREAD

**Issue by andrewangelle** [lost-pixel/lost-pixel#261]
### Mode

Storybook

### Feature description

Couldn't find anything in documentation or examples for this. Please correct me if I missed this somewhere.

**Request:** An ability to skip screenshots for an individual story. Other similar tools will respect a flag on the story parameters. Something like the following...
```typescript
const ExampleStory = {
  title: 'Story Title',
  component: MyComponent,
  parameters: {
    lostPixel: {
      skip: true
    }
  }
}
```

**Comment by d-ivashchuk** [comment]
Hey @andrewangelle! it would be: 

```
lostpixel: { disable: true },
```

I will document this better, thanks for the heads up!
