### ISSUE TITLE
Allow multiple browsers

### ISSUE THREAD

**Issue by joshferrell** [lost-pixel/lost-pixel#335]
### Mode

None

### Feature description

In the lost-pixel.config.js allow multiple browsers to be sent in as an array:
```
import type { CustomProjectConfig } from 'lost-pixel'

export const config: CustomProjectConfig = {
  browser: ['chromium', 'firefox', 'safari'],
  storybookShots: {
    storybookUrl: './storybook-static',
  },
  generateOnly: true,
}
```

For design systems, it's common that visual regression tests are run on all browsers. It'd be great if we didn't have to setup multiple configurations of lost-pixel for each browser.

**Comment by d-ivashchuk** [comment]
Hey Josh! I think it would be not so hard to add this feature to lost pixel, in a similar fashion to what we do with breakpoints. Do you want to give it a go? I could setup you up and explain how to run lost pixel locally
