### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by chbiel** [lost-pixel/lost-pixel#340]
### Bug description

As of now it looks like there is no active maintenance anymore for this repo, am I correct?

Easily resolvable but blocking issues are open for more then 2 months (e.g. https://github.com/lost-pixel/lost-pixel/issues/327).
PR's are also open without comments for over a month.

So currently it does not look to be a good idea to use or even buy lost-pixel.

So what about maintenance? Are there any active maintainer out there? :)

### How to reproduce

look at issues and PRs

**Comment by d-ivashchuk** [comment]
hey @chbiel! very much maintained, I was not able to easily reproduce the issue and we were focusing on the SaaS offering of Lost Pixel right now more. `lost-pixel` is pretty stable and is used by numerous OSS and commercial companies & we are intending to maintain it actively.

**Comment by chbiel** [comment]
ok good to know and thanks for the quick answer ;) 
The documentation somehow indicates, that this repo is actively used within your SaaS application. But if it's a separate application / repo, it makes the oss version less interesting, as the support will always be second prio. For us it would maybe be the door opener to consider using the platform.

I will add a comment to the linked bug, how to reproduce it quickly

**Comment by d-ivashchuk** [comment]
@chbiel just for the reference - `lost-pixel` is the core for the our platform, so support here shall and will always be a prio. Consider this hiccup me being sidetracked by different prios for now :D We value both our OSS users & paid customers the same and want to provide stellar vis reg testing tooling!

**Comment by chbiel** [comment]
Ok @d-ivashchuk  :) I only wanted to ask and kindly reflect that, the oss `lost-pixel` is somehow the display window to your paid platform. And when I try to install it and the first 2 things are errors (where one can only be solved by pinning another dependency to an older version), this first impression is automatically transfered to the SaaS platform (at least for my personal experiences).

But all in all, thanks for answering quickly and clearifing :)

**Comment by d-ivashchuk** [comment]
great feedback, put some additional line into docs & will fix the dep issue soon!
