### ISSUE TITLE
[Bug] : Set Active toggle not accessible on mobile device

### ISSUE THREAD

**Issue by AdityaJamdade** [lost-pixel/lost-pixel#368]
### Bug description

This is a styling issue.
On mobile devices the 'Set active' toggle button is not visible. Only the repository name is there but the button is going out of the viewport.

### How to reproduce

1. Login with github.
2. Authorize the application.
3. Install the lost-pixel app for all repositories.
4. When navigating through the list of repositories we can see that 'Set Active' Button is not visible

![image](https://github.com/lost-pixel/lost-pixel/assets/89738016/c3fcc8b1-ec8d-4fbf-a818-4f777bab2709)

### Expected behavior

**'Set active' toggle bar should be visible completely.**

**Comment by d-ivashchuk** [comment]
Hey @AdityaJamdade, Lost Pixel is currently not intended to be used on mobile devices. It is still possible to use it with some limitations due to the UI not being super responsive, but I would not recommend it.

**Comment by AdityaJamdade** [comment]
okay @d-ivashchuk, then should I just close the issue as Not planned?

**Comment by d-ivashchuk** [comment]
Yeah, might be reasonable!

**Comment by AdityaJamdade** [comment]
Cool!
