### ISSUE TITLE
Screenshot locator

### ISSUE THREAD

**Issue by pedrosousa13** [lost-pixel/lost-pixel#370]
### Mode

Storybook

### Feature description

I am evaluating this project as well as test-runner for our visual regression. I have set up quite an advanced system in test-runner until I found your project. 

If this feature is interesting I can also make a PR for it.

We have a locator just before a screenshot is taken so that our components can fully be in the viewport like so:
`const image = await page.locator('#storybook-root > *').first().screenshot({...`

I would love to control this since it allows us to take a screenshot of the exact component we need making our comparisons more accurate.

I was thinking of adding a `screenshotLocator` to the config that would allow people to set their own locator like:
`await page.screenshotLocator().screenshot(....`

What do you think?

**Comment by d-ivashchuk** [comment]
Hey Pedro! looks quite interesting on the surface, would love to get to understand the use-case a little bit more 🙌🏼

So, do you use the locator to make a snapshot of the direct element via some selector, or do you just want to make sure that page is scrolled to that element? I got a little bit confused here, maybe an example with the screenshot itself could help me understand it a bit more 🙏🏼

Other than that, I would absolutely welcome the contribution and assist you with everything if the feature makes sense to be added on the general top level.

I am thinking if you wouldn't be able to achieve the same with what we provide already, e.g. beforeScreenshot that has access to playwright browser.

**Comment by pedrosousa13** [comment]
Thank you for the quick reply!

We want to make a snapshot of a direct element since we built a design system of atomic components :)

Let me give you an example:

![Screenshot 2024-01-19 at 09 43 33](https://github.com/lost-pixel/lost-pixel/assets/4235827/bf411b12-121b-42c8-8f6b-5988e990e8b0)

In this case we only want to take a screenshot of the button. It works really well on test-runner. Our components are quite small sometimes and having a huge viewport messes with the statistical pixel matching

**Comment by d-ivashchuk** [comment]
Ah, snap, absolute blast of the feature! so basically we would be able to provide the concrete locator of the element that we want to test for all our tests.

 Let's take a step back and see how you use the feature in your org & how we can make it adaptable to all modes of lost-pixel(except custom)
 
 Do you have it set up only once, and then whenever the storybook is opened, some wrapper takes care that it is snapshotted, or do you have it different per story?

**Comment by pedrosousa13** [comment]
It works in our case for all because we only 1 component per story. It's the only thing stopping us from using lost-pixel OSS so it would be great to have 😄

**Comment by pedrosousa13** [comment]
I could see a value in having it per story/page though 😄

**Comment by d-ivashchuk** [comment]
We could start here:

https://github.com/lost-pixel/lost-pixel/blob/fa98610c1e179c2b13c01d1e1bb147f2206b1b36/src/shots/shots.ts#L130-L137

https://github.com/lost-pixel/lost-pixel/blob/1645f989995739ef2b874477927fdce768b55789/src/types.ts#L5-L26

In page.screenshot we are making the screenshot so locator would reside there(my first guess)

ShotItem will need to be extended as well so it can somehow consume the locator by itself.

Finally:

https://github.com/lost-pixel/lost-pixel/blob/b089ab2d63b16e521104fadf71aada2657f09298/src/config.ts#L33-L152

config on the top level would also need to be able to consume it.

Meaning the logic would be the following:

Look for locator at config level(in storybookshots, ladleshots, pageshots, etc.), if it is not there, look for it at the level of the shotitem, and then consume when screenshoting

**Comment by d-ivashchuk** [comment]
@pedrosousa13 we are already having a bloat of features that are different across the modes, so if we can make it really centralised & nicely fitting at least storybook & pages mode, would be amazing.

Also go try lost-pixel.com :D you will definitely enjoy it

**Comment by pedrosousa13** [comment]
Again, thank you so much for the support :)

**Comment by d-ivashchuk** [comment]
closed in #371

**Comment by alexandrutatarciuc** [comment]
Looks like a great feature!
@d-ivashchuk Any news on when this could be released? 😇
