### ISSUE TITLE
Running `lost-pixel docker update` expects `lostpixel.config.ts` but docs states `lost-pixel.config.ts` (with the dash)

### ISSUE THREAD

**Issue by SrBrahma** [lost-pixel/lost-pixel#373]
### Bug description

When I run `lost-pixel docker update`, I have

![image](https://github.com/lost-pixel/lost-pixel/assets/28177550/e2bb9cb3-804e-44a8-b27b-f64ec1183b84)

But the docs have

![image](https://github.com/lost-pixel/lost-pixel/assets/28177550/816023a6-6036-4df7-8996-6300ee93c2bc)

https://docs.lost-pixel.com/user-docs/setup/project-configuration/modes#storybook

Should the docs be updated to not have the dash on the filename? I can PR it if you want!

### Lost Pixel information

"lost-pixel": "3.13.0",

**Comment by d-ivashchuk** [comment]
good catch, mind updating that? :D shall be without dash
