### ISSUE TITLE
Installing Lost Pixel as dependency breaks Storybook

### ISSUE THREAD

**Issue by SrBrahma** [lost-pixel/lost-pixel#374]
### Bug description

This is more of an initial Issue as I don't know how to repro it yet, sorry. But it might be useful for the records.

When I install `lost-pixel` as a devDep, my `storybook` command stops working with this error:

![image](https://github.com/lost-pixel/lost-pixel/assets/28177550/043afe34-d7b6-414c-9d0c-fa38241fcdb9)

If I uninstall `lost-pixel` and clean `node_modules`, the storybook command works again.

I believe that there might be an internal dependency that is causing some sort of conflict with the storybook build system, maybe with babel/webpack.

There is this quite related old issue, but I don't know how it can help:
https://github.com/storybookjs/storybook/issues/11291

For now I will be running the lost-pixel without installing it, with `bunx`. It works this way!

Although, I lose access to the types, but not a big deal. I am having the config file as .js now.

![image](https://github.com/lost-pixel/lost-pixel/assets/28177550/a471078e-b7f0-45c7-a7c6-474623660f1c)

### Lost Pixel information

    "@storybook/addon-a11y": "6.5.16",
    "@storybook/addon-actions": "6.5.16",
    "@storybook/addon-controls": "6.5.16",
    "@storybook/addon-essentials": "6.5.16",
    "@storybook/addons": "6.5.16",
    "@storybook/builder-webpack4": "6.5.16",
    "@storybook/manager-webpack4": "6.5.16",
    "@storybook/react": "6.5.16",
    
    "lost-pixel": "3.13.0",

**Comment by d-ivashchuk** [comment]
That's totally weird, we don't have dependencies on storybook, but there might be some mutual one indeed. Did you try with some other storybook version?

**Comment by SrBrahma** [comment]
Upgrading it isn't viable at the moment as it would require migrating many stories, although it's planned. Although I believe it would fix this issue.

I will close it as I don't see how we can further investigate it and upgrading it would possibly fix it, but I think it's useful already to have this issue here available for others to find it, if someone steps in the same problem.
