### ISSUE TITLE
Crawl static site to find new pages

### ISSUE THREAD

**Issue by IanVS** [lost-pixel/lost-pixel#392]
### Mode

Page screenshots

### Feature description

I'm trying out lost pixel, coming from Percy snapshots.  I'm trying to find a way to automatically snapshot all pages, including newly-added pages, without having to update a configuration array in `lostpixel.config.ts`.  Is that possible?  If not, how do people usually manage the workflow?  Do they always just try to remember to add new pages to the config?  

Or, is there a way to automatically find and snapshot all pages?  If not, is this a feature you'd consider adding?  Otherwise, I'm not sure how useful this tool will be to me.

**Comment by d-ivashchuk** [comment]
Hey Ian! You can construct pages dynamically and process in lost pixel or you can even point lost pixel to a json array of pages that lives separately in the application.

are you able to construct the list of pages yourself? If the answer is yes you can integrate pretty easily with lost pixel.

I also like the Sitemap approach that would make it semiautomatic, check this out please:

https://www.lost-pixel.com/blog/simplifying-next-js-visual-regression-testing

**Comment by IanVS** [comment]
Ah perfect, I'll give the sitemap approach a whirl.  Appreciate it!

**Comment by d-ivashchuk** [comment]
Would love to help with any questions! Feel free to ping anytime and good luck playing with Sitemaps and lost pixel 🙌🏼

**Comment by d-ivashchuk** [comment]
Cool that you figured it out 🙌🏼 I think it's a misconfig on our side not to allow pages as undefined when you provide them via external json. Also good catch on the side of the versioning and our templates, will update that!
