### ISSUE TITLE
Add hooks

### ISSUE THREAD

**Issue by levchak0910** [lost-pixel/lost-pixel#395]
### Mode

Other

### Feature description

I would like to suggest adding a new feature to the project configuration.

The feature request is to add hooks. Under hook I mean some subscription on events that are happening under the hood and executing some user logic. Example: [Nuxt hooks](https://nuxt.com/docs/guide/going-further/hooks)

Suggested configuration:

```ts
import type { CustomProjectConfig } from "lost-pixel"

export const config: CustomProjectConfig = {
  // ...
  hooks: {
    "<hook-name>": async function (args) {
      await doSomethingWithArgs(args)
    },
  },
}
```

The expected process flow:

1. executing lib logic
2. executing user hook logic (the process is stopped until the hook handler is not resolved)
3. executing lib logic
4. ....
5. finish the process

**My case**: I would like to edit generated screenshots before making a comparison. Usually, I use visual comparison for checking the state of reusable components, most of the time they are much bigger than the viewport. So I wrote a script that executes on provided images and can "trim" empty spaces (pixels with white color, from all sides until a row or column with at least 1 pixel with non-white color). I want to execute this script after screenshots were generated, but before the comparison started.

Would it be useful to add such a feature (hooks) to your library?
If the suggested feature is out of the library's scope, could you share please any other way how I can achieve the desired behavior?

**Comment by d-ivashchuk** [comment]
hey! interesting idea in general, can see the application across various hooks and events. 

i think currently you could do it in beforeTheScreenshot though, or? did you check it out?

**Comment by d-ivashchuk** [comment]
i would be more than happy to accept the PR with after screenshot as well as extending element selector for non multi root components - gotta start somewhere, right? 😀 if you would require any help, i am here for you anytime!

**Comment by levchak0910** [comment]
Hi @d-ivashchuk
I have implemented the desired behavior, waiting for your review )

During development I had a problem with differences on how the headless browser in CI renders the screenshots compared to my local machine. How you usually solve this differences (which one you choose for baseline image)?

**Comment by d-ivashchuk** [comment]
we either take them from test artefacts, or alternatively we run the tests with  docker update 

https://docs.lost-pixel.com/user-docs/guides/testing-and-updating-baseline-locally

**Comment by levchak0910** [comment]
ah, clear, thanks
I committed them from CI and then merge --squash-ed them into commit

would be great if you can mention it in CONTRIBUTING.md
