### ISSUE TITLE
Ability to pass a custom Browser executable path to playwright for pageShots

### ISSUE THREAD

**Issue by n2o1988** [lost-pixel/lost-pixel#402]
### Mode

Page screenshots

### Feature description

Hi! First, `lost-pixel` is very cool, thank you a lot for building it! 
In my project, I've specific versions of browsers (Chrome, Chromium, Firefox) already installed in a custom location. 
I can use the `PLAYWRIGHT_BROWSERS_PATH` environment variable to point Playwright to that as the root, but it still looks for a pre-defined version of Chromium, leading to the following error:

> Prepared 1 pages for screenshots on chromium
❌ browserType.launch: Executable doesn't exist at /var/tmp/.browsers-cache/chromium-1091/chrome-mac/Chromium.app/Contents/MacOS/Chromium

Note, that I _don't_ want to install yet another version of Chrome/Chromium. 

Would it be possible to add an option to the lost-pixel configuration file, where you can specify the version or (even better in my case) the full path to the executable binary? You can do that by passing an [executablePath prop](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-executable-path)  to the [launch method here](https://github.com/lost-pixel/lost-pixel/blob/main/src/shots/shots.ts#L224).

More generically, you could just accept a `browserLaunchOptions` object in the configuration file and pass that to the `launch` command.

Thanks in advance!

**Comment by d-ivashchuk** [comment]
this sounds like a great idea in general. we currently don't allow custom versions of chromium indeed but i would be open to the contribution to make it flexible. 

from the top of my head i can't see anything that would prevent the custom version but there might be some limitations overall that are unforeseen. need to try it out!

**Comment by n2o1988** [comment]
Yeah, just like Playwright's [documentation](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-executable-path) says, this is something that users should use at their own risk:
<img width="919" alt="image" src="https://github.com/user-attachments/assets/2fe5639e-a48a-4250-93b1-016207132da8">

In my case, I'm already using a specific version of Chromium, with playwright, to perform traditional end-to-end testing on the application so I know it would work for my use case.

**Comment by d-ivashchuk** [comment]
do you mind contributing this? would love to merge it if it's flexible enough not to touch the general logic.

**Comment by n2o1988** [comment]
@d-ivashchuk I've pushed a PR that implements this. I tried to follow the contributing guidelines. Let me know if it looks ok: https://github.com/lost-pixel/lost-pixel/issues/402

**Comment by chriskalmar** [comment]
Released in https://github.com/lost-pixel/lost-pixel/releases/tag/v3.19.0
