### ISSUE TITLE
Retry screenshots

### ISSUE THREAD

**Issue by FezVrasta** [lost-pixel/lost-pixel#446]
### Mode

Storybook

### Feature description

It would be very useful if there was an option to retry the screenshots if the comparison fails. Sometimes stories are flaky and retrying a single one is much quicker than retrying the whole spec.

**Comment by bartekczyz** [comment]
@FezVrasta it's not documented very well, but you can use `flakynessRetries` in your `lostpixel.config.ts` file

```ts
export const config: CustomProjectConfig = {
  // ...
  flakynessRetries: 3,
};

```

**Comment by FezVrasta** [comment]
oh awesome, thanks!
